### ISSUE TITLE
[BUG] `changed-files` error during run

### ISSUE THREAD

**Issue by ozlotusflare** [tj-actions/changed-files#875] opened 2022-12-16 15:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Hi everyone, 
I updated action to latest version and from time to time I see these logs
```bash
/runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 189:   490 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 190:   528 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 191:   560 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 192:   596 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 193:   630 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 194:   668 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 195:   701 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 196:   736 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 197:   772 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
```
and it skip modified file.
Now I got next:
```bash
changed-files
  Resolving repository path: /runner/_work/test.
  Retrieving changes between b553bfcafe64c0ee6f3e1f4a15bec6ac5abf3098 (master) → a017cfa4ab7934d79037cfc860719b05029c40e8 (update-actions-gh)
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 189:   490 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 190:   528 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 191:   560 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 192:   596 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 193:   630 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 194:   668 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 195:   701 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 196:   736 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 197:   772 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 91: echo: write error: Broken pipe
  Error: Process completed with exit code 1.
```
So, I don’t get it why it sometimes checks changed files sometimes skipped .. 

### To Reproduce

Created PR with modified file yaml file
My action config:
```yaml
- name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.yaml
            **/*.yml
```
Do some changes in file and run actions, and repeat 

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Run without exceptions and track every time when file was changed 

### Relevant log output

```shell
...
a017cfa4ab7934d79037cfc860719b05029c40e8 (update-actions-gh)
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 189:   490 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 190:   528 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 191:   560 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 192:   596 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v34/get-changed-paths.sh: line 193:   630 Killed                  grep -x -E -f 
...
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment] 2022-12-16 20:41
@ozlotusflare Can you enable debugging when posted logs as outlined here
<img width="650" alt="Screenshot 2022-12-16 at 1 41 24 PM" src="https://user-images.githubusercontent.com/17484350/208185485-ff9bea9c-5aa6-4e43-8a5a-0f9bfcb9a0cd.png">

**Comment by jackton1** [comment] 2022-12-16 20:59
@eltociear Closing this issue, for now since a new version has been released. Let me know if the issue persists and I can reopen the issue. I also recommend that you enable debugging and post the entire log output i.e including the checkout and the changed files actions steps

**Comment by ozlotusflare** [comment] 2022-12-19 16:05
Hi @jackton1, thank you for your reply, I checked new (35)version and still I have issues at the same place:
`checkout output`
```bash
##[debug]Evaluating condition for step: 'Run actions/checkout@v3'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run actions/checkout@v3
##[debug]Register post job cleanup for action: actions/checkout@v3
##[debug]Loading inputs
##[debug]Evaluating: github.repository
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'repository'
##[debug]=> 'test/test'
##[debug]Result: 'test/test'
##[debug]Evaluating: github.token
##[debug]Evaluating Index:
##[debug]..Evaluating github:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'token'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Loading env
Run actions/checkout@v3
##[debug]GITHUB_WORKSPACE = '/runner/_work/test'
##[debug]qualified repository = 'test/test'
##[debug]ref = 'refs/pull/30757/merge'
##[debug]commit = '9[2](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:2)42[3](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:3)887[4](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:4)7cc6fbdd38860[5](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:5)fac042af4f7309c29'
##[debug]clean = true
##[debug]fetch depth = 0
##[debug]lfs = false
##[debug]submodules = false
##[debug]recursive submodules = false
##[debug]GitHub Host URL = 
::add-matcher::/runner/_work/_actions/actions/checkout/v3/dist/problem-matcher.json
##[debug]Added matchers: 'checkout-git'. Problem matchers scan action output for known warning or error strings and report these inline.
Syncing repository: test/test
::group::Getting Git version info
Getting Git version info
  Working directory is '/runner/_work/test'
  ##[debug]Getting git version
  /usr/bin/git version
  git version 2.38.2
  ##[debug]Set git useragent to: git/2.38.2 (github-actions-checkout)
  ::endgroup::
::add-mask::***
Temporarily overriding HOME='/runner/_work/_temp/5958c81c-50cc-4181-9d[6](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:6)b-5438b34868ef' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /runner/_work/test/
Deleting the contents of '/runner/_work/test/test'
::group::Initializing the repository
Initializing the repository
::group::Disabling automatic garbage collection
Disabling automatic garbage collection
::group::Setting up auth
Setting up auth
::group::Fetching the repository
Fetching the repository
::group::Determining the checkout info
Determining the checkout info
::group::Checking out the ref
Checking out the ref
  /usr/bin/git checkout --progress --force refs/remotes/pull/30[7](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:7)57/merge
  Note: switching to 'refs/remotes/pull/30757/merge'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  HEAD is now at 92423[8](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:8)8747 Merge 82430c7340806a1ae0e6465b5f[9](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:9)c1e859409027e into 3f[12](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:12)b8b92c6375786ded1ab93e993e95945adfe7
  ::endgroup::
/usr/bin/git log -1 --format='%H'
'924[23](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:23)88747cc6fbdd[38](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:39)8605fac0[42](https://github.com/test/test/actions/runs/3731558811/jobs/6330010580#step:3:43)af4f7309c29'
##[debug]Unsetting HOME override
::remove-matcher owner=checkout-git::
##[debug]Removed matchers: 'checkout-git'
##[debug]Node Action run completed with exit code 0
##[debug]Save intra-action state isPost = true
##[debug]Save intra-action state setSafeDirectory = true
##[debug]Save intra-action state repositoryPath = /runner/_work/test
##[debug]Finishing: Run actions/checkout@v3
```
`changed-files-debug`
```bash
changed-files
  Resolving repository path: /runner/_work/test.
  Retrieving changes between 3f12b8b92c6375786ded1ab93e993e95945adfe7 (master) → 9242388747cc6fbdd388605fac042af4f7309c29 (update-actions-gh)
  /runner/_work/_actions/tj-actions/changed-files/v35/get-changed-paths.sh: line 185:   485 Killed                  grep -x -E -f "$INPUT_FILES_PATTERN_FILE"
  /runner/_work/_actions/tj-actions/changed-files/v35/get-changed-paths.sh: line 87: echo: write error: Broken pipe
  Error: Process completed with exit code 1.
  ##[debug]Finished: run
  ##[debug]Evaluating: steps.changed-files.outputs.added_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'added_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.copied_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'copied_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.deleted_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'deleted_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.modified_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'modified_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.renamed_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'renamed_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.all_old_new_renamed_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'all_old_new_renamed_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.type_changed_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'type_changed_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.unmerged_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'unmerged_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.unknown_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'unknown_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.all_changed_and_modified_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'all_changed_and_modified_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.all_changed_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'all_changed_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.any_changed
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'any_changed'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.only_changed
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'only_changed'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.other_changed_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'other_changed_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.all_modified_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'all_modified_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.any_modified
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'any_modified'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.only_modified
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'only_modified'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.other_modified_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'other_modified_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.any_deleted
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'any_deleted'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.only_deleted
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'only_deleted'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Evaluating: steps.changed-files.outputs.other_deleted_files
  ##[debug]Evaluating Index:
  ##[debug]..Evaluating Index:
  ##[debug]....Evaluating Index:
  ##[debug]......Evaluating steps:
  ##[debug]......=> Object
  ##[debug]......Evaluating String:
  ##[debug]......=> 'changed-files'
  ##[debug]....=> Object
  ##[debug]....Evaluating String:
  ##[debug]....=> 'outputs'
  ##[debug]..=> Object
  ##[debug]..Evaluating String:
  ##[debug]..=> 'other_deleted_files'
  ##[debug]=> null
  ##[debug]Result: null
  ##[debug]Finishing: Get changed files
```
Thank you!

**Comment by jackton1** [comment] 2022-12-19 16:12
@ozlotusflare Can you create a public repository which replicates the error you are having?
it would be helpful to fill in all the missing details like your workflow setup and the directory structure. Thanks

**Comment by ozlotusflare** [comment] 2022-12-19 16:15
Sure, I'll ping you out.

**Comment by AlbericTrancart** [comment] 2023-01-18 08:44
@jackton1 I found the root cause. It is an error on my part, I was using a file pattern on a folder that doesn't exist (running the action with `files: adage/**` when the target folder was `adage-front`.
So now it's fixed on my side but it can be an improvement for the action to have a better error message in this case :slightly_smiling_face:

**Closed** 2023-01-18 18:54 UTC
Labels: bug
