### ISSUE TITLE
[BUG] Argument list too long with files input

### ISSUE THREAD

**Issue by jacobrask** [tj-actions/changed-files#367] opened 2022-02-14 22:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

A couple of thousands files matching the input filter is too long, causing the following error:

```
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/...'. Argument list too long
```

I believe it is happening at `bash $GITHUB_ACTION_PATH/entrypoint.sh` in the action.

### To Reproduce

Run the action and match a lot of files.

```
      - uses: tj-actions/changed-files@v14.6
        with:
          files: **/*
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

The glob action could pass the patterns to changed-files as a temporary file instead of as an environment variable.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment] 2022-02-14 23:50
@jacobrask I'll recommend skipping the `files: **/*` entirely if you're expecting to detect changes to all files.

**Comment by jacobrask** [comment] 2022-02-15 06:20
> @jacobrask I'll recommend skipping the `files: **/*` entirely if you're expecting to detect changes to all files.
> 
> 
> 
> See a usage example here 👉🏾  https://github.com/tj-actions/changed-files/pull/376.
> 
> 
> 
> For passing patterns via a file on disk. See: [Inputs](https://github.com/tj-actions/changed-files#inputs) `files_from_source_file`.

I'm not, it was just an example. I'm skipping 1/10 files or so in the repository, it's a large one.

**Comment by jacobrask** [comment] 2022-02-15 06:22
Using `files_from_source_file` won't help because the crash happens between the glob action and this action.

**Comment by jackton1** [comment] 2022-02-15 06:47
Let me know if it's resolved in the latest release which has a number of significant updates.

**Comment by jackton1** [comment] 2022-02-15 06:59
Can you also include the logs that would be helpful in debugging?

**Comment by jacobrask** [comment] 2022-02-15 07:23
Ok I'll try the latest release, but pretty sure it's hitting a bash limit here. Getting some other hits when searching "Argument list too long", such as https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867

Full logs

```
Run tj-actions/changed-files@v14.6
Run # "Set base sha..."
Run tj-actions/glob@v7
Run actions/github-script@v6
Run bash $GITHUB_ACTION_PATH/entrypoint.sh
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/...'. Argument list too long


If I expand "Run bash"

Run bash $GITHUB_ACTION_PATH/entrypoint.sh
  bash $GITHUB_ACTION_PATH/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    GITHUB_SERVER_URL: https://github.com
    GITHUB_REPOSITORY: xxx
    GITHUB_BASE_REF: master
    INPUT_SHA: xxx
    INPUT_BASE_SHA: 
    INPUT_TOKEN: ***
    INPUT_FILES_PATTERN: 
      LONG LIST OF FILES
    INPUT_SEPARATOR:  
    INPUT_PATH: 
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/...'. Argument list too long
```

**Comment by mosherc** [comment] 2022-03-03 17:07
I am also having this issue with this simple example:
```
        with:
          files: |
            src/scripts/**/*.js
```
Why is this issue closed if it's still happening?

**Comment by jackton1** [comment] 2022-03-08 11:43
### Helpful Resources
- https://unix.stackexchange.com/questions/83260/reading-grep-patterns-from-a-file
- https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867
- https://linux.die.net/man/1/grep

**Comment by jackton1** [comment] 2022-03-08 12:10
> I am also having this issue with this simple example:
> 
> ```
>         with:
>           files: |
>             src/scripts/**/*.js
> ```
> 
> Why is this issue closed if it's still happening?

It was closed due to a lack of providing any reproducible information.

**Comment by jackton1** [comment] 2022-03-08 12:10
Based on the community answer a possible resolution would be to write the entire lisr of files to a temp file and clean it up after using it.

This should 
- write to /tmp/...
- Pass the output file to the changed-files action
- Run grep using the `-f` flag (Investigate if exact match using `-x` would work with extended regex which would replace the use of `^(patterns)$`.)

### Helpful Resources
- https://unix.stackexchange.com/questions/83260/reading-grep-patterns-from-a-file
- https://github.community/t/maximum-length-for-the-comment-body-in-issues-and-pr/148867
- https://linux.die.net/man/1/grep

**Comment by genieai-vikas** [comment] 2022-03-08 12:29
@jackton1 Sorry I didn't get this part. 
`Run grep using the -f flag (Investigate if exact match using -x would work with extended regex which would replace the use of ^(patterns)$.)`
Can we have a sample snippet for this workaround

**Comment by genieai-vikas** [comment] 2022-03-09 10:07
@jackton1 I tried what you suggested above still getting the same error.

1. Write a list of files of directories into a temp file
2. passed the file  like this

```
      - name: check if BE MS changed
        uses: tj-actions/changed-files@v9.3
        id: be_changed_files
        with:
          files_from_source_file: |
            changed-files-list.txt
```

```
    INPUT_SEPARATOR:  
Error: An error occurred trying to start process '/usr/bin/bash' with working directory '/home/runner/work/genie-app/genie-app'. Argument list too long
```

**Comment by jackton1** [comment] 2022-03-09 12:12
@genieai-vikas Oh no this isn’t a work around you need to implement it’s one Its the changed I have to implement before this can be resolved.1

**Closed** 2022-03-14 05:01 UTC
Labels: bug

**Comment by jackton1** [comment] 2022-03-14 05:02
@jacobrask @mosherc @genieai-vikas This should be resolved in the latest release.

**Comment by jackton1** [comment] 2022-05-25 21:43
Related Issue: #502
