### ISSUE TITLE
[BUG] Not detecting changed files on pull request type closed

### ISSUE THREAD

**Issue by Sohaib112** [tj-actions/changed-files#1380] opened 2023-07-14 10:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

For the following code, it is working as expected. 
```
name: 'Apply'

on:
  pull_request:
    types:
      - opened
      - synchronize
      
jobs:
  terraform_apply:
    name: Apply the plan 
    runs-on: self-hosted

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            terraform/applications/**
          dir_names: "true"

      - name: List all changed files
        id: changed-apps
        run: |
          CHANGED_AND_MODIFIED_PATHS="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          echo $CHANGED_AND_MODIFIED_PATHS
```

the output is showing the path:
```
Run CHANGED_AND_MODIFIED_PATHS="terraform/applications/logging"
terraform/applications/logging
```

But when I change the same code for `pull_request` `type` `closed`. It doesn't bring the path
```
name: 'Apply'

on:
  pull_request:
    types:
      - closed
      
jobs:
  terraform_apply:
    name: Apply the plan 
    runs-on: self-hosted

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: |
            terraform/applications/**
          dir_names: "true"

      - name: List all changed files
        id: changed-apps
        run: |
          CHANGED_AND_MODIFIED_PATHS="${{ steps.changed-files.outputs.all_changed_and_modified_files }}"
          echo $CHANGED_AND_MODIFIED_PATHS

```

```
Run CHANGED_AND_MODIFIED_PATHS=""
```

Debug logs
```
##[debug]Evaluating condition for step: 'List all changed files'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: List all changed files
##[debug]Loading inputs
##[debug]Evaluating: format('CHANGED_AND_MODIFIED_PATHS="{0}"
##[debug]echo $CHANGED_AND_MODIFIED_PATHS', steps.changed-files.outputs.all_changed_and_modified_files)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'CHANGED_AND_MODIFIED_PATHS="{0}"
##[debug]echo $CHANGED_AND_MODIFIED_PATHS'
##[debug]..Evaluating Index:
##[debug]....Evaluating Index:
##[debug]......Evaluating Index:
##[debug]........Evaluating steps:
##[debug]........=> Object
##[debug]........Evaluating String:
##[debug]........=> 'changed-files'
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'outputs'
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'all_changed_and_modified_files'
##[debug]..=> ''
##[debug]=> 'CHANGED_AND_MODIFIED_PATHS=""
##[debug]echo $CHANGED_AND_MODIFIED_PATHS'
##[debug]Result: 'CHANGED_AND_MODIFIED_PATHS=""
##[debug]echo $CHANGED_AND_MODIFIED_PATHS'
##[debug]Loading env
```

### To Reproduce

Use the workflows to reproduce the error.

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

Should give the modified path

### Relevant log output

```shell
Already added the debug logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment] 2023-07-14 11:34
@Sohaib112 can you provide the full logs with debugging enabled.

Also curious is there a reason you are using an old version of the checkout action?

**Comment by jackton1** [comment] 2023-07-14 14:19
Closing this for now pending response as I’m unable to reproduce the bug. Here’s a recent run for pull_request close event https://github.com/tj-actions/changed-files/actions/runs/5546920935/jobs/10127900655#step:5:1.

**Closed by jackton1** 2023-07-14 14:19 UTC
Labels: bug, not-reproducible
